version: "3"
services:
    web:
        build: ./api/DiplomApi
        ports:
            - "5000:80"
        depends_on:
            - db
    db:
        build: "./docker/db"
        environment:
            SA_PASSWORD: "poquePASS1234"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
    client:
        build: "./client"
        volumes:
          - ./client:/app:rw,cached
        ports:
          - "3000:3000"
    nginx:
        build: ./docker/nginx
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
        ports: 
            - "80:80"
        depends_on:
            - client
            - web

